language: python
python:
    - "2.7"

install:
    - 'if [ ${TRAVIS_BRANCH} = "master" ]; then
        pip install --extra-index-url https://testpypi.python.org/pypi -r src/requirements.txt;
      else
        pip install --extra-index-url https://testpypi.python.org/pypi -r dev_requirements.txt;
      fi'
    - pip install -r test_requirements.txt
    - pip install coveralls

script:
    - python runtests.py --with-coverage  --cover-package=src

after_success:
    - coveralls
